# Generated by Django 4.2.4 on 2023-08-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plugins', '0014_alter_plugin_app_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHoursConfiguration',
            fields=[
                ('basepluginconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plugins.basepluginconfiguration')),
                ('show_map', models.BooleanField(default=True, verbose_name='show map on open hours page')),
            ],
            options={
                'verbose_name': 'open hours configuration',
                'verbose_name_plural': 'open hours configurations',
            },
            bases=('plugins.basepluginconfiguration',),
        ),
    ]
