# Generated by Django 4.2.4 on 2023-08-17 19:44

import apps.files.storage
import apps.open_hours.models.configuration
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plugins', '0014_alter_plugin_app_label'),
        ('sections', '0015_alter_sectionsconfiguration_required_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHoursConfiguration',
            fields=[
                ('basepluginconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plugins.basepluginconfiguration')),
                ('show_map', models.BooleanField(default=True, verbose_name='show map on open hours page')),
                ('map', models.ImageField(blank=True, null=True, storage=apps.files.storage.NamespacedFilesStorage('open-hours-map', has_permission=apps.open_hours.models.configuration.has_perms_to_view_map), upload_to=apps.files.storage.NamespacedFilesStorage.upload_to, verbose_name='map')),
            ],
            options={
                'verbose_name': 'open hours configuration',
                'verbose_name_plural': 'open hours configurations',
            },
            bases=('plugins.basepluginconfiguration',),
        ),
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('day_index', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_hours', to='sections.section')),
            ],
            options={
                'verbose_name': 'open hours',
                'verbose_name_plural': 'open hours',
                'ordering': ('day_index', 'from_time'),
            },
        ),
    ]
