# Generated by Django 4.2.4 on 2023-08-17 12:56

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('open_hours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('day_index', models.PositiveSmallIntegerField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'open hours',
                'verbose_name_plural': 'open hours',
                'ordering': ('day_index', 'from_time'),
            },
        ),
    ]
