# Generated by Django 4.2.4 on 2023-08-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0015_alter_sectionsconfiguration_required_gender_and_more'),
        ('open_hours', '0002_openhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhours',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='open_hours', to='sections.section'),
            preserve_default=False,
        ),
    ]
