# Generated by Django 4.2.4 on 2023-08-17 13:55

import apps.files.storage
import apps.open_hours.models.configuration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_hours', '0003_openhours_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='openhoursconfiguration',
            name='map',
            field=models.ImageField(blank=True, null=True, storage=apps.files.storage.NamespacedFilesStorage('open-hours-map', has_permission=apps.open_hours.models.configuration.has_perms_to_view_map), upload_to=apps.files.storage.NamespacedFilesStorage.upload_to, verbose_name='map'),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='day_index',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
    ]
