default_language_version:
  python: python3.9

repos:
  # basic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # security linter on
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: Security check by bandit
        args: [ '-iii', '-ll' ]

  # linter & complexity analyzer
  # not used the default, since it doesn't currently support pyproject.toml
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v0.0.1a4
    hooks:
      - id: pyproject-flake8
        name: Code & complexity linting by flake8
        exclude: '.*/migrations/.*'
        additional_dependencies: [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-print",
            "flake8-simplify",
        ]

  # uncompromise python formatter
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: Code formatter black
        exclude: ^.*\b(migrations)\b.*$

#  - repo: https://github.com/pycqa/isort
#    rev: 5.10.1
#    hooks:
#      - id: isort
#        name: Sort all imports by isort

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
  autofix_prs: false
  autoupdate_branch: develop
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [ ]
  submodules: false
