default_language_version:
  python: python3.11

repos:
  # basic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^charts/templates/
        args:
          - --allow-multiple-documents
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]

  # security linter on
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: check security by Bandit
        args: [ '-iii', '-ll' ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.282'
    hooks:
      - id: ruff
        name: lint by Ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  # uncompromise python formatter
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: format by black
        exclude: ^.*\b(migrations)\b.*$

  - repo: https://github.com/Riverside-Healthcare/djlint
    rev: 'v1.32.1'  # replace with the latest tag on GitHub
    hooks:
      - id: djlint-django
        entry: djlint  --reformat

  - repo: https://github.com/ecugol/pre-commit-hooks-django
    rev: v0.4.0  # Use the ref you want to point at
    hooks:
      - id: check-untracked-migrations
        name: check no untracked migration

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
  autofix_prs: false
  autoupdate_branch: develop
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip:
    - check-untracked-migrations  # no git there on CI
  submodules: false
