version: '3.3'
services:
  web:
    command: [ sh, "-c", "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000" ]
    environment:
      DJANGO_CONFIGURATION: Production

  webserver:
    command: [ nginx, '-g', 'daemon off;' ]
    environment:
      STATIC_LOCATION_PATTERN: '^/static/(.*)$$'

  webpack:
    command: yarn build
    environment:
      NODE_ENV: production
      PUBLIC_PATH: https://fiesta.local/static/

  dockerproxy:
    ports:
      - "80:80"
      - "443:443"
    # TODO: figure out before deployment, whereever/where should be certs stored
    volumes:
      - ./conf/certs:/etc/nginx/certs

  # remove profiles so production env does have filled elastic search
#  elastic:
#    profiles: [ ]

#  wikifetcher:
#    profiles: [ ]
