version: '3.3'
services:
  web:
    build:
      # collectstatic done be dockerfile
      target: web-stable
    environment:
      DJANGO_CONFIGURATION: LocalProduction

  proxy:
    build:
      target: proxy-stable
    command: [ nginx, '-g', 'daemon off;' ]
    environment:
      STATIC_LOCATION_PATTERN: '^/static/(.*)$$'

  webpack:
    profiles:
      - do-not-start

  dockerproxy:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/certs:/etc/nginx/certs
