version: '3.3'
services:
  web:
    build:
      # collectstatic done be dockerfile
      target: web-stable
    environment:
      DJANGO_CONFIGURATION: LocalProduction

  proxy:
    build:
      target: proxy-stable
    command: [ nginx, '-g', 'daemon off;' ]
    environment:
      STATIC_LOCATION_PATTERN: '^/static/(.*)$$'

  webpack:
    profiles:
      - do-not-start

  dockerproxy:
    ports:
      - "80:80"
      - "443:443"
    # TODO: figure out before deployment, whereever/where should be certs stored
    volumes:
      - ./conf/certs:/etc/nginx/certs

  # remove profiles so production env does have filled elastic search
#  elastic:
#    profiles: [ ]

#  wikifetcher:
#    profiles: [ ]
