# Generated by Django 4.0.2 on 2022-02-12 13:02

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plugins", "0001_initial"),
        ("sections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("esncards", "0001_initial"),
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ESNcardsConfiguration",
            fields=[
                (
                    "basepluginconfiguration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="plugins.basepluginconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "esncards configuration",
                "verbose_name_plural": "esncards configurations",
            },
            bases=("plugins.basepluginconfiguration",),
        ),
        migrations.AddField(
            model_name="esncardapplication",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="sections.section",
                verbose_name="section",
            ),
        ),
        migrations.AddField(
            model_name="esncardapplication",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="universities.university",
                verbose_name="university",
            ),
        ),
        migrations.AddField(
            model_name="esncardapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="issuer",
            ),
        ),
    ]
