# Generated by Django 4.0.2 on 2022-02-22 13:46

from django.db import migrations, models

import apps.files.storage


class Migration(migrations.Migration):

    dependencies = [
        ('esncards', '0003_esncardapplication_passport_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esncardapplication',
            name='passport_picture',
        ),
        migrations.AddField(
            model_name='esncardapplication',
            name='holder_photo',
            field=models.ImageField(default=None, help_text='Front passport-sized photo is needed.', storage=apps.files.storage.NamespacedFilesStorage('esncard-application-picture'), upload_to=apps.files.storage.NamespacedFilesStorage.upload_to, verbose_name='holder photo'),
            preserve_default=False,
        ),
    ]
