# Generated by Django 4.2 on 2023-04-08 22:15

import apps.esncards.models.application
import apps.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esncards', '0004_remove_esncardapplication_passport_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esncardapplication',
            name='holder_photo',
            field=models.ImageField(help_text='Front passport-sized photo is needed.', storage=apps.files.storage.NamespacedFilesStorage('esncard-application-picture', has_permission=apps.esncards.models.application.has_permission_to_view_holder_photo), upload_to=apps.files.storage.NamespacedFilesStorage.upload_to, verbose_name='holder photo'),
        ),
    ]
