# Generated by Django 4.2.4 on 2023-08-18 16:28

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0015_alter_sectionsconfiguration_required_gender_and_more'),
        ('esncards', '0006_alter_esncardapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sections.section', verbose_name='section')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='esncardapplication',
            name='export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='esncards.export', verbose_name='part of export'),
        ),
    ]
