# Generated by Django 4.2.4 on 2023-08-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esncards', '0007_export_esncardapplication_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('prepared', 'Prepared'), ('exported', 'Exported')], default='created', max_length=20, verbose_name='state'),
        ),
    ]
