# Generated by Django 4.2 on 2023-04-09 21:00

from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields
import django_extensions.db.fields
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plugins', '0013_alter_plugin_app_label'),
        ('sections', '0013_alter_section_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesConfiguration',
            fields=[
                ('basepluginconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plugins.basepluginconfiguration')),
            ],
            options={
                'verbose_name': 'pages configuration',
                'verbose_name_plural': 'pages configurations',
            },
            bases=('plugins.basepluginconfiguration',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=128, verbose_name='page title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='url slug')),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(verbose_name='content')),
                ('order', models.PositiveSmallIntegerField(blank=True, verbose_name='order of display')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.page')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pages', to='sections.section', verbose_name='section')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
