# Generated by Django 4.2 on 2023-04-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_page_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug_path',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(models.F('section'), models.F('slug'), name='pages_slug_section_page_unique'),
        ),
    ]
