# Generated by Django 4.2 on 2023-04-10 12:57

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_slug_path_page_pages_slug_section_page_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.page', verbose_name='parent page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(verbose_name='url slug'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug_path',
            field=models.CharField(default='', editable=False, max_length=128, verbose_name='path from slugs in page tree'),
        ),
    ]
