# Generated by Django 4.2.7 on 2023-11-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_page_parent_alter_page_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('section', 'order', 'title'), 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterField(
            model_name='page',
            name='default',
            field=models.BooleanField(default=None, help_text="If set, this page will be displayed on section's base URL; only one page can be default for section.", null=True, verbose_name='default page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug_path',
            field=models.CharField(default='', editable=False, max_length=128, verbose_name='url path in page tree'),
        ),
    ]
