# Generated by Django 4.0.2 on 2022-02-12 13:02

import uuid

import django.db.models.deletion
import django_countries.fields
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='full name of university')),
                ('abbr', models.SlugField(allow_unicode=True, max_length=32, verbose_name='abbreviation of university name')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country of university')),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'universities',
                'ordering': ('country', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='full name of faculty (w/o university)', max_length=128, verbose_name='name of faculty')),
                ('abbr', models.SlugField(allow_unicode=True, max_length=16, verbose_name='abbreviation of faculty name')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='universities.university', verbose_name='related university')),
            ],
            options={
                'verbose_name': 'faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ('university', 'name'),
            },
        ),
    ]
