# Generated by Django 4.2.7 on 2023-11-14 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_alter_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='faculties', to='universities.university', verbose_name='related university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
