{{ $data := dict
  "Name"   .Values.ingress.dnsWebhookSecretName
  "Values" (dict
    "SCW_DNS_ACCESS_KEY" (.Values.secrets.dnsWebhook.accessKey | b64enc)
    "SCW_DNS_SECRET_KEY" (.Values.secrets.dnsWebhook.secretKey | b64enc)
  )
}}
{{- include "fiesta.secret" (merge (dict "Args" $data) . ) -}}
