apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.ingress.certIssuerName | quote }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.ingress.certContactEmail }}
    privateKeySecretRef:
      name: {{ .Values.ingress.certIssuerSecretName }}
    solvers:
      - dns01:
          webhook:
            groupName: acme.scaleway.com
            solverName: scaleway
            config:
              # Only needed if you don't have default credentials as seen above.
              accessKeySecretRef:
                key: SCW_DNS_ACCESS_KEY
                name: {{ .Values.ingress.dnsWebhookSecretName | quote }}
              secretKeySecretRef:
                key: SCW_DNS_SECRET_KEY
                name: {{ .Values.ingress.dnsWebhookSecretName | quote }}
{{/*      - http01:*/}}
{{/*          ingress:*/}}
{{/*            class: nginx*/}}
