apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiesta-ingress
  labels:
    {{- include "fiesta.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/issuer: {{ .Values.ingress.certIssuerName | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
        {{- .Values.ingress.extraHosts | toYaml | nindent 8 }}
      secretName: {{ .Values.ingress.certSecretName | quote }}
  rules:
    - host: "*.{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http
