apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiesta-ingress
  labels:
    {{- include "fiesta.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/issuer: {{ .Values.ingress.certIssuerName | quote }}
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: web
      port:
        number: 80
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
        {{- .Values.ingress.extraHosts | toYaml | nindent 8 }}
      secretName: {{ .Values.ingress.certSecretName | quote }}
