apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiesta-ingress
spec:
  rules:
    - host: "*.bf.josefkolar.cz"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
    - host: "bf.josefkolar.cz"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
