apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.web.configName }}
  labels:
    {{- include "fiesta.labels" . | nindent 4 }}
data:
  DJANGO_CONFIGURATION: "Production"
  DJANGO_ROOT_DOMAIN: {{ .Values.ingress.host | quote }}
