{{ $data := dict
  "Name"   .Values.web.secretName
  "Values" (dict
    "DJANGO_SECRET_KEY" (randAlphaNum 48 | b64enc)

    "DJANGO_DATABASE_URL" (.Values.secrets.databaseUrl | b64enc)

    "DJANGO_AWS_S3_ACCESS_KEY_ID" (.Values.secrets.s3.keyId | b64enc)
    "DJANGO_AWS_S3_SECRET_ACCESS_KEY" (.Values.secrets.s3.accessKey | b64enc)
    "DJANGO_AWS_S3_REGION_NAME" (.Values.secrets.s3.regionName | b64enc)
    "DJANGO_AWS_STORAGE_BUCKET_NAME" (.Values.secrets.s3.bucketName | b64enc)
    "DJANGO_SENTRY_DSN" (.Values.secrets.sentry.dsn | b64enc)
    "DJANGO_SENTRY_JS_LOADER_URL" (.Values.secrets.sentry.jsLoaderUrl | b64enc)
  )
}}
{{- include "fiesta.secret" (merge (dict "Args" $data) . ) -}}
