apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    {{- include "fiesta.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
