apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    {{- include "fiesta.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fiesta.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: web
        {{- include "fiesta.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-logs-container: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.repository }}:{{ .Values.web.tag | default .Chart.AppVersion }}"
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
          envFrom:
            - secretRef:
                name: {{ .Values.web.secretKeyName }}
            - secretRef:
                name: {{ .Values.web.secretDbName }}
            - configMapRef:
                name: {{ .Values.web.configName }}
        - name: proxy
          image: "{{ .Values.proxy.repository }}:{{ .Values.proxy.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
