apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    {{- include "fiesta.labels" . | nindent 4 }}
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
