apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    {{- include "fiesta.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "fiesta.selectorLabels" . | nindent 4 }}
    {{- include "fiesta.componentLabels" "web" | nindent 4 }}
  ports:
    - port: 80
      name: http
      targetPort: proxy
