# Generated by Django 4.0.2 on 2022-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmembership',
            name='state',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('suspended', 'Suspended')], default='inactive', max_length=16, verbose_name='membership state'),
        ),
    ]
