# Generated by Django 4.0.2 on 2022-07-23 15:54

from django.db import migrations, models
from django.utils.text import slugify


def set_defaults(apps, schema_editor):
    Section = apps.get_model('sections', 'Section')

    for section in Section.objects.all().iterator():
        section.space_slug = section.code or slugify(section.name)
        section.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_alter_section_code_alter_sectionmembership_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='space_slug',
            field=models.SlugField(blank=True, help_text='Slug used for defining section spaces.', null=True, unique=True, verbose_name='space slug'),
        ),
        migrations.RunPython(set_defaults)
    ]
