# Generated by Django 4.0.2 on 2022-07-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_section_space_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='space_slug',
            field=models.SlugField(help_text='Slug used for defining section spaces as URL subdomains.', unique=True, verbose_name='space slug'),
        ),
    ]
