# Generated by Django 4.0.6 on 2022-07-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_alter_section_space_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionmembership',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'verbose_name': 'section membership', 'verbose_name_plural': 'section memberships'},
        ),
        migrations.AlterField(
            model_name='sectionmembership',
            name='role',
            field=models.CharField(choices=[('international', 'International'), ('member', 'Member'), ('editor', 'Editor'), ('admin', 'Admin')], max_length=16, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='sectionmembership',
            name='state',
            field=models.CharField(choices=[('inactive', 'Unconfirmed'), ('active', 'Confirmed'), ('suspended', 'Suspended')], default='inactive', max_length=16, verbose_name='state'),
        ),
    ]
