# Generated by Django 4.0.6 on 2022-07-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_alter_sectionmembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionsconfiguration',
            name='required_gender',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=is required, False=is optional, None=not available', null=True, verbose_name='required gender'),
        ),
        migrations.AddField(
            model_name='sectionsconfiguration',
            name='required_nationality',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=is required, False=is optional, None=not available', null=True, verbose_name='required nationality'),
        ),
        migrations.AddField(
            model_name='sectionsconfiguration',
            name='required_picture',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=is required, False=is optional, None=not available', null=True, verbose_name='required profile picture'),
        ),
    ]
