# Generated by Django 4.0.6 on 2022-08-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_sectionsconfiguration_required_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionsconfiguration',
            options={'verbose_name': 'section configuration', 'verbose_name_plural': 'section configurations'},
        ),
    ]
