# Generated by Django 4.1 on 2022-08-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0009_alter_sectionsconfiguration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionsconfiguration',
            name='auto_approved_membership_for_international',
            field=models.BooleanField(default=True, help_text='Decides, wheever is membership requested by user automatically approved for internationalusers (e.g. during registration process or requested by membership form.', verbose_name='auto approved membership for international'),
        ),
    ]
