# Generated by Django 4.1 on 2022-08-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0010_sectionsconfiguration_auto_approved_membership_for_international'),
        ('sections', '0010_sectionsconfiguration_required_phone_number'),
    ]

    operations = [
    ]
