# Generated by Django 4.2 on 2023-04-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0012_section_system_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('name',), 'verbose_name': 'ESN section', 'verbose_name_plural': 'ESN sections'},
        ),
        migrations.AddField(
            model_name='sectionsconfiguration',
            name='required_interests',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=is required, False=is optional, None=not available', null=True, verbose_name='required interests'),
        ),
        migrations.AlterField(
            model_name='sectionsconfiguration',
            name='auto_approved_membership_for_international',
            field=models.BooleanField(default=True, help_text='Decides, whenever is membership requested by user automatically approved for international users (e.g. during registration process or requested by membership form).', verbose_name='auto approved membership for international'),
        ),
    ]
