# Generated by Django 4.2 on 2023-04-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0013_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmembership',
            name='role',
            field=models.CharField(choices=[('international', 'International'), ('member', 'Member'), ('editor', 'Editor'), ('admin', 'Admin'), ('alumni', 'Alumni')], max_length=16, verbose_name='role'),
        ),
    ]
