# Generated by Django 4.2.4 on 2023-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0014_alter_sectionmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsconfiguration',
            name='required_gender',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=field is required, False=field is optional, None=field is not available', null=True, verbose_name='required gender'),
        ),
        migrations.AlterField(
            model_name='sectionsconfiguration',
            name='required_interests',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=field is required, False=field is optional, None=field is not available', null=True, verbose_name='required interests'),
        ),
        migrations.AlterField(
            model_name='sectionsconfiguration',
            name='required_nationality',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=field is required, False=field is optional, None=field is not available', null=True, verbose_name='required nationality'),
        ),
        migrations.AlterField(
            model_name='sectionsconfiguration',
            name='required_phone_number',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=field is required, False=field is optional, None=field is not available', null=True, verbose_name='required phone number'),
        ),
        migrations.AlterField(
            model_name='sectionsconfiguration',
            name='required_picture',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=field is required, False=field is optional, None=field is not available', null=True, verbose_name='required profile picture'),
        ),
    ]
