# Generated by Django 4.2.7 on 2023-11-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0015_alter_sectionsconfiguration_required_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmembership',
            name='state',
            field=models.CharField(choices=[('inactive', 'Unconfirmed'), ('active', 'Active'), ('suspended', 'Suspended')], default='inactive', max_length=16, verbose_name='state'),
        ),
    ]
