# Generated by Django 4.2.7 on 2023-11-14 12:47

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0019_alter_sectionsconfiguration_required_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='sectionmembership',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='sectionuniversity',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
