# Generated by Django 4.2.7 on 2023-11-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_faculty_created_alter_faculty_university_and_more'),
        ('sections', '0020_alter_section_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionuniversity',
            name='section',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='section_universities', to='sections.section', verbose_name='ESN section'),
        ),
        migrations.AlterField(
            model_name='sectionuniversity',
            name='university',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='university_sections', to='universities.university', verbose_name='university'),
        ),
    ]
