# Generated by Django 4.2.7 on 2023-12-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0022_sectionsconfiguration_required_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='allow_experimental_plugins',
            field=models.BooleanField(default=False, verbose_name='allow experimental plugins'),
        ),
    ]
