# Generated by Django 4.2.28 on 2026-03-08 12:00
from __future__ import annotations

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sections", "0024_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionsconfiguration",
            name="email_digest_interval",
            field=models.DurationField(
                default=datetime.timedelta(hours=24),
                validators=[django.core.validators.MinValueValidator(datetime.timedelta(minutes=1))],
                verbose_name="How often to send the 'new members waiting' digest",
            ),
        ),
    ]
