from __future__ import annotations

INTERESTS_CHOICES = (
    ("music", "🎶 Music"),
    ("photo", "📸 Photography"),
    ("IT", "🧑‍💻 IT"),
    ("party", "🎉 Partying"),
    ("food", "🍲 Food"),
    ("coffee", "☕ Coffee"),
    ("travel", "✈ Travelling"),
    ("dance", "💃 Dancing"),
    ("video-making", "🎥 Video-making"),
    ("football", "⚽ Football"),
    ("movies", "🎞️ Movies"),
    ("running", "🏃‍♀️ Running"),
    ("reading", "📚️ Reading"),
    ("shopping", "🛍️️ Shopping"),
    ("hiking", "⛰️ Hiking"),
    ("pets", "🐕️ Pets"),
    ("volleyball", "🏐️ Volleyball"),
    ("self-development", "🧑📚️ Self-development"),
    ("theatre", "🎭️ Theatre"),
    ("yoga", "🧘️ Yoga"),
    ("fashion", "🧥️ Fashion"),
    ("architecture", "🏛️️ Architecture"),
    ("tik-tok", "🤡️️ TikTok scrolling"),
    ("writing", "✍️ Writing"),
    ("gaming", "🎮 Gaming"),
    ("cooking", "🍳 Cooking"),
    ("baking", "🧁 Baking"),
    ("painting", "🎨 Painting"),
    ("drawing", "✏️ Drawing"),
    ("sewing", "🧵 Sewing"),
    ("knitting", "🧶 Knitting"),
    ("crocheting", "🪡 Crocheting"),
    ("pottery", "🏺 Pottery"),
    ("sculpture", "🗿 Sculpture"),
    ("woodworking", "🪵 Woodworking"),
    ("metalworking", "🔨 Metalworking"),
    ("coding", "💻 Coding"),
    ("web_development", "🌐 Web Development"),
    ("graphic design", "🎨 Graphic Design"),
    ("animation", "🎬 Animation"),
    ("filmmaking", "🎥 Filmmaking"),
    ("acting", "🎭 Acting"),
    ("singing", "🎤 Singing"),
    ("karaoke", "🎤 Karaoke"),
    ("video_editing", "🎞️ Video Editing"),
    ("podcasting", "🎙️ Podcasting"),
    ("biking", "🚴 Biking"),
    ("skateboarding", "🛹 Skateboarding"),
    ("surfing", "🏄 Surfing"),
    ("snowboarding", "🏂 Snowboarding"),
    ("skiing", "⛷️ Skiing"),
    ("swimming", "🏊 Swimming"),
    ("diving", "🤿 Diving"),
    ("rock_climbing", "🧗 Rock Climbing"),
    ("parkour", "🤸 Parkour"),
    ("basketball", "🏀 Basketball"),
    ("soccer", "⚽ Soccer"),
    ("tennis", "🎾 Tennis"),
    ("golf", "⛳ Golf"),
    ("table_tennis", "🏓 Table Tennis"),
    ("badminton", "🏸 Badminton"),
    ("cricket", "🏏 Cricket"),
)
