ingress:
  certSecretName: fiesta-cert

  certIssuerName: scaleway
  certIssuerSecretName: cert-issuer-key
  dnsWebhookSecretName: scaleway-dns

  certContactEmail: dummy@example.com

  host: fiesta.plus
  extraHosts:
    - "*.fiesta.plus"

web:
  repository: nginxdemos/hello
  tag: latest

  configName: web-config
  secretName: web-secret

  port: 8000

proxy:
  repository: nginxdemos/hello
  tag: latest

  port: 80

secrets:
  databaseUrl: postgres
  s3:
    keyId: key
    accessKey: key
    regionName: region
    bucketName: bucket
  dnsWebhook:
    accessKey: key
    secretKey: key
