ingress:
  host: bf.josefkolar.cz
  certName: fiesta
  certSecretName: fiesta-cert
  certIssuerName: letsencrypt
  certIssuerSecretName: cert-issuer-key

  certContactEmail: dummy@example.com

service:
  port: 80

web:
  repository: nginxdemos/hello
  tag: latest

  secretKeyName: web-secret-key
  configName: web-config
  secretDbName: web-secret-db

proxy:
  repository: nginxdemos/hello
  tag: latest

cert-manager:
  enabled: true
  namespace: cert-manager
