ingress:
  host: bf.josefkolar.cz

service:
  port: 80

web:
  repository: nginxdemos/hello
  tag: latest

  secretKeyName: web-secret-key
  configName: web-config
  secretDbName: web-secret-db

proxy:
  repository: nginxdemos/hello
  tag: latest
