# Generated by Django 4.0.2 on 2022-02-13 18:04

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsconfiguration',
            name='required_nationality',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if nationality is needed to fill in user profile: True=is required, False=is optional, None=not available', null=True, verbose_name='required nationality'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('incomplete', 'Filled'), ('complete', 'Filled')], default='incomplete', max_length=16, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='nationality'),
        ),
    ]
