# Generated by Django 4.0.2 on 2022-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountsconfiguration_required_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsconfiguration',
            name='required_gender',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if nationality is needed to fill in user profile: True=is required, False=is optional, None=not available', null=True, verbose_name='required gender'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('decline_to_state', 'decline to state'), ('other', 'other')], max_length=16, null=True, verbose_name='nationality'),
        ),
    ]
