# Generated by Django 4.0.2 on 2022-02-18 19:30

import pathlib

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountsconfiguration_required_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(pathlib.PurePosixPath('/usr/src/media/profile-picture')), upload_to='', verbose_name='profile picture image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('decline_to_state', 'decline to state'), ('other', 'other')], max_length=16, null=True, verbose_name='gender'),
        ),
    ]
