# Generated by Django 4.0.2 on 2022-02-21 10:24

from django.db import migrations, models

import apps.files.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_picture_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=apps.files.storage.NamespacedFilesStorage('profile-picture'), upload_to=apps.files.storage.NamespacedFilesStorage.upload_to, verbose_name='profile picture image'),
        ),
    ]
