# Generated by Django 4.0.6 on 2022-07-27 17:28

from django.db import migrations, models

import apps.files.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_home_university_or_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=apps.files.storage.NamespacedFilesStorage('profile-picture'), upload_to=apps.files.storage.NamespacedFilesStorage.upload_to, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('incomplete', 'Uncompleted'), ('complete', 'Completed')], default='incomplete', max_length=16, verbose_name='state'),
        ),
    ]
