# Generated by Django 4.0.6 on 2022-07-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_picture_alter_userprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsconfiguration',
            name='required_picture',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if nationality is needed to fill in user profile: True=is required, False=is optional, None=not available', null=True, verbose_name='required profile picture'),
        ),
    ]
