# Generated by Django 4.0.6 on 2022-07-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accountsconfiguration_required_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsconfiguration',
            name='required_gender',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=is required, False=is optional, None=not available', null=True, verbose_name='required gender'),
        ),
        migrations.AlterField(
            model_name='accountsconfiguration',
            name='required_nationality',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=is required, False=is optional, None=not available', null=True, verbose_name='required nationality'),
        ),
        migrations.AlterField(
            model_name='accountsconfiguration',
            name='required_picture',
            field=models.BooleanField(blank=True, default=None, help_text='Flag if field is needed to fill in user profile: True=is required, False=is optional, None=not available', null=True, verbose_name='required profile picture'),
        ),
    ]
