# Generated by Django 4.0.6 on 2022-07-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_accountsconfiguration_required_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountsConfiguration',
        ),
    ]
