# Generated by Django 4.2 on 2023-04-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userprofile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('decline_to_state', 'decline to state'), ('other', 'other')], max_length=16, verbose_name='gender'),
        ),
    ]
