# Generated by Django 4.2 on 2023-04-24 19:36

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='facebook profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator('^[\\w_-.]+$')], verbose_name='instagram username'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, help_text='Phone number or username', verbose_name='telegram contact'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='whatsapp phone number'),
        ),
    ]
