# Generated by Django 4.2.4 on 2023-10-27 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_userprofile_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator('^[\\w_.]+$')], verbose_name='instagram username'),
        ),
    ]
