# Generated by Django 4.2.4 on 2023-10-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_alter_university_name'),
        ('accounts', '0018_alter_userprofile_instagram'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='home_university_or_faculty',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='guest_faculty',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='home_faculty',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='home_university',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='faculty_user_profiles', to='universities.faculty', verbose_name='faculty'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='university_user_profiles', to='universities.university', verbose_name='university'),
        ),
    ]
