# Generated by Django 4.2.7 on 2023-12-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_userprofile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(blank=True, help_text='Username or profile link: john.doe or https://www.facebook.com/john.doe', verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Username or profile link: john.doe or https://www.instagram.com/john.doe', verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, help_text='Username, phone, or profile: john.doe, +420777888999 or https://t.me/john.doe', verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Phone: +420777888999', verbose_name='whatsapp'),
        ),
    ]
