# Generated by Django 4.2.7 on 2023-12-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_slug',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='avatar slug'),
        ),
    ]
