# Generated by Django 4.2.8 on 2024-01-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_userprofile_avatar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_slug',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='avatar slug'),
        ),
    ]
