# Generated by Django 4.2.8 on 2024-01-23 20:16

import apps.accounts.models.profile
import apps.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_userprofile_avatar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture_height',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='profile picture width'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture_width',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='profile picture width'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, height_field='picture_height', null=True, storage=apps.files.storage.NamespacedFilesStorage('profile-picture', has_permission=apps.accounts.models.profile.has_permission_for_profile_picture_view), upload_to=apps.files.storage.NamespacedFilesStorage.upload_to, verbose_name='profile picture', width_field='picture_width'),
        ),
    ]
