# Generated by Django 4.2.28 on 2026-03-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_userprofile_picture_height_userprofile_picture_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='email notifications'),
        ),
    ]
