# Generated by Django 4.2.4 on 2023-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', help_text='full description of the event', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=models.TextField(blank=True, default='', help_text='short description of the event', verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Descriptions of the place or directions', max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Link to the place', max_length=256, verbose_name='webpage link'),
        ),
        migrations.AlterField(
            model_name='place',
            name='map_link',
            field=models.CharField(blank=True, default='', help_text='Link to a position to the place on a map', max_length=256, verbose_name='map link'),
        ),
    ]
