# Generated by Django 4.2.4 on 2023-09-30 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_event_description_alter_event_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='state',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('confirmed', 'Confirmed'), ('deleted', 'Deleted')], default='waiting', help_text='current state of the event', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='events.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='events.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='price',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='events.pricevariant', verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='pricevariant',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_variants', to='events.event', verbose_name='event'),
        ),
    ]
