# Generated by Django 4.2.4 on 2023-11-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0020_alter_section_created_and_more'),
        ('events', '0005_alter_event_created_alter_organizer_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='sections.section', verbose_name='ESN section'),
        ),
    ]
