# Generated by Django 4.2.7 on 2023-11-27 16:53

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_place_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='49.1922443,16.6113382', max_length=63, verbose_name='Location'),
        ),
    ]
