# Generated by Django 4.2.7 on 2023-11-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_place_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
    ]
