# Generated by Django 4.2.7 on 2023-12-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='state',
        ),
        migrations.AddField(
            model_name='organizer',
            name='role',
            field=models.CharField(choices=[('event_leader', 'Event_leader'), ('oc', 'OC')], default='oc', help_text='current role of the user on event', verbose_name='role'),
        ),
    ]
