# Generated by Django 4.2.7 on 2023-12-04 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_remove_organizer_state_organizer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizers', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='place',
            name='map_link',
            field=models.CharField(blank=True, default='', help_text='Link to google maps in format google.com/maps/place/<place>/@<coordinates>/data', max_length=256, verbose_name='map link'),
        ),
    ]
