# Generated by Django 4.0.2 on 2022-02-12 13:02

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePluginConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(default='default', max_length=64, verbose_name='human readable name used for recognizing.')),
            ],
            options={
                'verbose_name': 'base configuration',
                'verbose_name_plural': 'base configuration',
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('state', models.CharField(choices=[('enabled', 'enabled'), ('read_only', 'read-only'), ('privileged_only', 'privileged users only'), ('disabled', 'disabled')], default='enabled', help_text='Current state of plugin - affects, if plugin could be displayed by international/member/editor/admin/at all.', max_length=16, verbose_name='plugin state')),
                ('app_label', models.CharField(choices=[('accounts', 'Accounts'), ('esncards', 'Esncards'), ('sections', 'Sections')], help_text='Defines system application, which specific plugin represents.', max_length=256, verbose_name='app label')),
                ('configuration', models.OneToOneField(blank=True, help_text='Defines, in which configuration specific plugin runs.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='plugin', to='plugins.basepluginconfiguration', verbose_name='plugin configuration')),
            ],
            options={
                'verbose_name': 'plugin',
                'verbose_name_plural': 'plugins',
            },
        ),
    ]
