# Generated by Django 4.0.2 on 2022-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepluginconfiguration',
            name='name',
            field=models.CharField(default='default', max_length=64, verbose_name='human readable name'),
        ),
    ]
