# Generated by Django 4.0.2 on 2022-07-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_alter_plugin_app_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='app_label',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('buddy_system', 'Buddy_System'), ('esncards', 'Esncards'), ('sections', 'Sections')], help_text='Defines system application, which specific plugin represents.', max_length=256, verbose_name='app label'),
        ),
    ]
