# Generated by Django 4.0.6 on 2022-07-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_alter_plugin_app_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='app_label',
            field=models.CharField(choices=[('accounts', 'Users'), ('buddy_system', 'Buddy System'), ('esncards', 'ESNcards'), ('sections', 'ESN section')], help_text='Defines system application, which specific plugin represents.', max_length=256, verbose_name='app label'),
        ),
    ]
