# Generated by Django 4.0.6 on 2022-07-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0006_alter_plugin_app_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='app_label',
            field=models.CharField(choices=[('buddy_system', 'Buddy System'), ('esncards', 'ESNcards'), ('sections', 'ESN section')], help_text='Defines system application, which specific plugin represents.', max_length=256, verbose_name='app label'),
        ),
    ]
