# Generated by Django 4.0.6 on 2022-08-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_sectionsconfiguration_required_gender_and_more'),
        ('plugins', '0007_alter_plugin_app_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepluginconfiguration',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sections.section', verbose_name='owner section'),
        ),
        migrations.AddField(
            model_name='basepluginconfiguration',
            name='shared',
            field=models.BooleanField(default=False, verbose_name='is shared between sections'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='app_label',
            field=models.CharField(choices=[('buddy_system', 'Buddy System'), ('esncards', 'ESNcard'), ('sections', 'ESN section')], help_text='Defines system application, which specific plugin represents.', max_length=256, verbose_name='app label'),
        ),
    ]
