# Generated by Django 4.0.6 on 2022-08-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0008_basepluginconfiguration_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='configuration',
            field=models.ForeignKey(blank=True, help_text='Defines, in which configuration specific plugin runs.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='plugins', to='plugins.basepluginconfiguration', verbose_name='plugin configuration'),
        ),
    ]
