# Generated by Django 4.1 on 2022-08-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0010_alter_plugin_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepluginconfiguration',
            options={'verbose_name': 'base configuration', 'verbose_name_plural': 'base configurations'},
        ),
        migrations.AlterField(
            model_name='basepluginconfiguration',
            name='shared',
            field=models.BooleanField(default=False, verbose_name='is available to share between sections'),
        ),
    ]
