# Generated by Django 4.1 on 2022-10-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0011_merge_20220823_1449'),
        ('plugins', '0011_alter_basepluginconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepluginconfiguration',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='configurations', to='sections.section', verbose_name='owner section'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='app_label',
            field=models.CharField(choices=[('buddy_system', 'Buddy System'), ('dashboard', 'Dashboard'), ('esncards', 'ESNcard'), ('sections', 'ESN section')], help_text='Defines system application, which specific plugin represents.', max_length=256, verbose_name='app label'),
        ),
    ]
