# Generated by Django 4.2 on 2023-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0012_alter_basepluginconfiguration_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='app_label',
            field=models.CharField(choices=[('buddy_system', 'Buddy System'), ('dashboard', 'Dashboard'), ('esncards', 'ESNcard'), ('pages', 'Pages'), ('sections', 'ESN section')], help_text='Defines system application, which specific plugin represents.', max_length=256, verbose_name='app label'),
        ),
    ]
