# Generated by Django 4.2.7 on 2023-11-14 12:47

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0015_alter_plugin_app_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
    ]
