# Generated by Django 4.2.7 on 2023-11-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0016_alter_plugin_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='app_label',
            field=models.CharField(choices=[('buddy_system', 'Buddy System'), ('dashboard', 'Dashboard'), ('sections', 'ESN section'), ('esncards', 'ESNcard'), ('events', 'Events'), ('pages', 'Pages'), ('pickup_system', 'Pickup System')], help_text='Defines system application, which specific plugin represents.', max_length=256, verbose_name='app label'),
        ),
    ]
