# Generated by Django 4.2.7 on 2023-11-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0017_alter_plugin_app_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='state',
            field=models.CharField(choices=[('enabled', 'enabled'), ('read_only', 'read-only'), ('privileged_only', 'privileged users only'), ('disabled', 'disabled')], db_index=True, default='enabled', help_text='Current state of plugin - affects, if plugin could be displayed by international/member/editor/admin/at all.', max_length=16, verbose_name='plugin state'),
        ),
    ]
