# Generated by Django 4.0.2 on 2022-07-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plugins', '0004_alter_plugin_app_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddySystemConfiguration',
            fields=[
                ('basepluginconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plugins.basepluginconfiguration')),
            ],
            options={
                'verbose_name': 'buddy system configuration',
                'verbose_name_plural': 'buddy system configurations',
            },
            bases=('plugins.basepluginconfiguration',),
        ),
    ]
