# Generated by Django 4.0.6 on 2022-07-29 12:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0003_buddyrequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('photo', '📸 Photography'), ('hiking', '⛰️ Hiking'), ('running', '🏃\u200d♀️ Running'), ('pets', '🐕️ Pets'), ('IT', '🧑\u200d💻 IT'), ('tik-tok', '🤡️️ TikTok scrolling'), ('volleyball', '🏐️ Volleyball'), ('video-making', '🎥 Video-making'), ('footbal', '⚽ Football'), ('dance', '💃 Dancing'), ('theatre', '🎭️ Theatre'), ('party', '🎉 Partying'), ('architecture', '🏛️️ Architecture'), ('music', '🎶 Music'), ('yoga', '🧘️ Yoga'), ('coffee', '☕ Coffee'), ('travel', '✈ Travelling'), ('fashion', '🧥️ Fashion'), ('self-development', '🧑📚️ Self-development'), ('movies', '🎞️ Movies'), ('reading', '📚️ Reading'), ('shopping', '🛍️️ Shopping'), ('food', '🍲 Food')], max_length=24), default=[], size=None, verbose_name='issuer interests'),
        ),
    ]
