# Generated by Django 4.0.6 on 2022-07-30 00:36

from django.db import migrations, models

import apps.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0004_buddyrequest_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='interests',
            field=apps.utils.models.fields.ArrayFieldWithDisplayableChoices(base_field=models.CharField(choices=[('music', '🎶 Music'), ('self-development', '🧑📚️ Self-development'), ('theatre', '🎭️ Theatre'), ('food', '🍲 Food'), ('IT', '🧑\u200d💻 IT'), ('yoga', '🧘️ Yoga'), ('party', '🎉 Partying'), ('tik-tok', '🤡️️ TikTok scrolling'), ('fashion', '🧥️ Fashion'), ('volleyball', '🏐️ Volleyball'), ('pets', '🐕️ Pets'), ('video-making', '🎥 Video-making'), ('architecture', '🏛️️ Architecture'), ('reading', '📚️ Reading'), ('footbal', '⚽ Football'), ('running', '🏃\u200d♀️ Running'), ('photo', '📸 Photography'), ('hiking', '⛰️ Hiking'), ('travel', '✈ Travelling'), ('coffee', '☕ Coffee'), ('movies', '🎞️ Movies'), ('shopping', '🛍️️ Shopping'), ('dance', '💃 Dancing')], default=None, max_length=24), default=list, size=None, verbose_name='issuer interests'),
        ),
    ]
