# Generated by Django 4.0.6 on 2022-08-02 20:45

from django.db import migrations, models

import apps.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0005_alter_buddyrequest_interests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buddyrequest',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'verbose_name': 'buddy request', 'verbose_name_plural': 'buddy requests'},
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='interests',
            field=apps.utils.models.fields.ArrayFieldWithDisplayableChoices(base_field=models.CharField(choices=[('reading', '📚️ Reading'), ('IT', '🧑\u200d💻 IT'), ('movies', '🎞️ Movies'), ('party', '🎉 Partying'), ('yoga', '🧘️ Yoga'), ('travel', '✈ Travelling'), ('volleyball', '🏐️ Volleyball'), ('running', '🏃\u200d♀️ Running'), ('self-development', '🧑📚️ Self-development'), ('music', '🎶 Music'), ('fashion', '🧥️ Fashion'), ('theatre', '🎭️ Theatre'), ('coffee', '☕ Coffee'), ('video-making', '🎥 Video-making'), ('shopping', '🛍️️ Shopping'), ('dance', '💃 Dancing'), ('pets', '🐕️ Pets'), ('footbal', '⚽ Football'), ('food', '🍲 Food'), ('photo', '📸 Photography'), ('architecture', '🏛️️ Architecture'), ('tik-tok', '🤡️️ TikTok scrolling'), ('hiking', '⛰️ Hiking')], default=None, max_length=24), blank=True, default=list, size=None, verbose_name='issuer interests'),
        ),
    ]
