# Generated by Django 4.0.6 on 2022-08-02 21:15

from django.db import migrations, models

import apps.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0006_alter_buddyrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='interests',
            field=apps.utils.models.fields.ArrayFieldWithDisplayableChoices(base_field=models.CharField(choices=[('volleyball', '🏐️ Volleyball'), ('video-making', '🎥 Video-making'), ('self-development', '🧑📚️ Self-development'), ('party', '🎉 Partying'), ('hiking', '⛰️ Hiking'), ('IT', '🧑\u200d💻 IT'), ('fashion', '🧥️ Fashion'), ('footbal', '⚽ Football'), ('architecture', '🏛️️ Architecture'), ('music', '🎶 Music'), ('running', '🏃\u200d♀️ Running'), ('theatre', '🎭️ Theatre'), ('shopping', '🛍️️ Shopping'), ('food', '🍲 Food'), ('movies', '🎞️ Movies'), ('travel', '✈ Travelling'), ('tik-tok', '🤡️️ TikTok scrolling'), ('dance', '💃 Dancing'), ('yoga', '🧘️ Yoga'), ('pets', '🐕️ Pets'), ('photo', '📸 Photography'), ('reading', '📚️ Reading'), ('coffee', '☕ Coffee')], default=None, max_length=24), blank=True, default=list, size=None, verbose_name='issuer interests'),
        ),
    ]
