# Generated by Django 4.0.6 on 2022-08-02 22:19

from django.db import migrations, models

import apps.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0007_alter_buddyrequest_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='interests',
            field=apps.utils.models.fields.ArrayFieldWithDisplayableChoices(base_field=models.CharField(choices=[('self-development', '🧑📚️ Self-development'), ('music', '🎶 Music'), ('video-making', '🎥 Video-making'), ('shopping', '🛍️️ Shopping'), ('volleyball', '🏐️ Volleyball'), ('tik-tok', '🤡️️ TikTok scrolling'), ('coffee', '☕ Coffee'), ('dance', '💃 Dancing'), ('photo', '📸 Photography'), ('theatre', '🎭️ Theatre'), ('yoga', '🧘️ Yoga'), ('party', '🎉 Partying'), ('running', '🏃\u200d♀️ Running'), ('fashion', '🧥️ Fashion'), ('food', '🍲 Food'), ('footbal', '⚽ Football'), ('travel', '✈ Travelling'), ('hiking', '⛰️ Hiking'), ('pets', '🐕️ Pets'), ('architecture', '🏛️️ Architecture'), ('reading', '📚️ Reading'), ('IT', '🧑\u200d💻 IT'), ('movies', '🎞️ Movies')], default=None, max_length=24), blank=True, default=list, size=None, verbose_name='issuer interests'),
        ),
    ]
