# Generated by Django 4.1 on 2022-08-05 15:10

import apps.utils.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0008_alter_buddyrequest_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='interests',
            field=apps.utils.models.fields.ArrayFieldWithDisplayableChoices(base_field=models.CharField(choices=[('photo', '📸 Photography'), ('shopping', '🛍️️ Shopping'), ('IT', '🧑\u200d💻 IT'), ('pets', '🐕️ Pets'), ('footbal', '⚽ Football'), ('movies', '🎞️ Movies'), ('reading', '📚️ Reading'), ('music', '🎶 Music'), ('theatre', '🎭️ Theatre'), ('running', '🏃\u200d♀️ Running'), ('video-making', '🎥 Video-making'), ('tik-tok', '🤡️️ TikTok scrolling'), ('food', '🍲 Food'), ('party', '🎉 Partying'), ('self-development', '🧑📚️ Self-development'), ('hiking', '⛰️ Hiking'), ('travel', '✈ Travelling'), ('dance', '💃 Dancing'), ('coffee', '☕ Coffee'), ('volleyball', '🏐️ Volleyball'), ('fashion', '🧥️ Fashion'), ('architecture', '🏛️️ Architecture'), ('yoga', '🧘️ Yoga')], default=None, max_length=24), blank=True, default=list, size=None, verbose_name='issuer interests'),
        ),
    ]
