# Generated by Django 4.1 on 2022-08-04 12:09

from django.db import migrations, models

import apps.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0008_alter_buddyrequest_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='interests',
            field=apps.utils.models.fields.ArrayFieldWithDisplayableChoices(base_field=models.CharField(choices=[('dance', '💃 Dancing'), ('running', '🏃\u200d♀️ Running'), ('travel', '✈ Travelling'), ('IT', '🧑\u200d💻 IT'), ('music', '🎶 Music'), ('shopping', '🛍️️ Shopping'), ('volleyball', '🏐️ Volleyball'), ('architecture', '🏛️️ Architecture'), ('coffee', '☕ Coffee'), ('yoga', '🧘️ Yoga'), ('movies', '🎞️ Movies'), ('video-making', '🎥 Video-making'), ('self-development', '🧑📚️ Self-development'), ('party', '🎉 Partying'), ('reading', '📚️ Reading'), ('photo', '📸 Photography'), ('fashion', '🧥️ Fashion'), ('tik-tok', '🤡️️ TikTok scrolling'), ('footbal', '⚽ Football'), ('pets', '🐕️ Pets'), ('hiking', '⛰️ Hiking'), ('theatre', '🎭️ Theatre'), ('food', '🍲 Food')], default=None, max_length=24), blank=True, default=list, size=None, verbose_name='issuer interests'),
        ),
    ]
