# Generated by Django 4.1 on 2022-08-05 15:29

import apps.utils.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0009_alter_buddyrequest_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='interests',
            field=apps.utils.models.fields.ArrayFieldWithDisplayableChoices(base_field=models.CharField(choices=[('running', '🏃\u200d♀️ Running'), ('travel', '✈ Travelling'), ('dance', '💃 Dancing'), ('IT', '🧑\u200d💻 IT'), ('footbal', '⚽ Football'), ('reading', '📚️ Reading'), ('video-making', '🎥 Video-making'), ('tik-tok', '🤡️️ TikTok scrolling'), ('volleyball', '🏐️ Volleyball'), ('hiking', '⛰️ Hiking'), ('shopping', '🛍️️ Shopping'), ('music', '🎶 Music'), ('party', '🎉 Partying'), ('fashion', '🧥️ Fashion'), ('pets', '🐕️ Pets'), ('photo', '📸 Photography'), ('self-development', '🧑📚️ Self-development'), ('food', '🍲 Food'), ('coffee', '☕ Coffee'), ('theatre', '🎭️ Theatre'), ('movies', '🎞️ Movies'), ('yoga', '🧘️ Yoga'), ('architecture', '🏛️️ Architecture')], default=None, max_length=24), blank=True, default=list, size=None, verbose_name='issuer interests'),
        ),
    ]
