# Generated by Django 4.1 on 2022-08-05 15:31

import apps.utils.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0010_alter_buddyrequest_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='interests',
            field=apps.utils.models.fields.ArrayFieldWithDisplayableChoices(base_field=models.CharField(choices=[('theatre', '🎭️ Theatre'), ('self-development', '🧑📚️ Self-development'), ('dance', '💃 Dancing'), ('food', '🍲 Food'), ('running', '🏃\u200d♀️ Running'), ('tik-tok', '🤡️️ TikTok scrolling'), ('video-making', '🎥 Video-making'), ('architecture', '🏛️️ Architecture'), ('reading', '📚️ Reading'), ('coffee', '☕ Coffee'), ('party', '🎉 Partying'), ('hiking', '⛰️ Hiking'), ('footbal', '⚽ Football'), ('fashion', '🧥️ Fashion'), ('music', '🎶 Music'), ('volleyball', '🏐️ Volleyball'), ('IT', '🧑\u200d💻 IT'), ('shopping', '🛍️️ Shopping'), ('photo', '📸 Photography'), ('pets', '🐕️ Pets'), ('travel', '✈ Travelling'), ('movies', '🎞️ Movies'), ('yoga', '🧘️ Yoga')], default=None, max_length=24), blank=True, default=list, size=None, verbose_name='issuer interests'),
        ),
    ]
