# Generated by Django 4.1 on 2022-10-01 17:15

from django.db import migrations, models

import apps.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0013_alter_buddyrequest_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='interests',
            field=apps.utils.models.fields.ArrayFieldWithDisplayableChoices(base_field=models.CharField(choices=[('hiking', '⛰️ Hiking'), ('yoga', '🧘️ Yoga'), ('shopping', '🛍️️ Shopping'), ('theatre', '🎭️ Theatre'), ('dance', '💃 Dancing'), ('tik-tok', '🤡️️ TikTok scrolling'), ('architecture', '🏛️️ Architecture'), ('music', '🎶 Music'), ('photo', '📸 Photography'), ('food', '🍲 Food'), ('self-development', '🧑📚️ Self-development'), ('video-making', '🎥 Video-making'), ('reading', '📚️ Reading'), ('party', '🎉 Partying'), ('volleyball', '🏐️ Volleyball'), ('coffee', '☕ Coffee'), ('IT', '🧑\u200d💻 IT'), ('footbal', '⚽ Football'), ('pets', '🐕️ Pets'), ('movies', '🎞️ Movies'), ('running', '🏃\u200d♀️ Running'), ('fashion', '🧥️ Fashion'), ('travel', '✈ Travelling')], default=None, max_length=24), blank=True, default=list, size=None, verbose_name='issuer interests'),
        ),
    ]
