# Generated by Django 4.2.4 on 2023-08-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0018_buddysystemconfiguration_display_request_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buddyrequest',
            options={'get_latest_by': 'modified', 'ordering': ('-created',), 'verbose_name': 'buddy request', 'verbose_name_plural': 'buddy requests'},
        ),
    ]
