# Generated by Django 4.2.4 on 2023-09-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0019_alter_buddyrequest_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buddyrequest',
            old_name='description',
            new_name='issuer_note',
        ),
    ]
