# Generated by Django 4.2.4 on 2023-09-24 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buddy_system', '0020_rename_description_buddyrequest_issuer_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyrequest',
            name='issuer_note',
        ),
        migrations.RemoveField(
            model_name='buddyrequest',
            name='matched_at',
        ),
        migrations.RemoveField(
            model_name='buddyrequest',
            name='matched_by',
        ),
        migrations.AddField(
            model_name='buddyrequest',
            name='note',
            field=models.TextField(default='', verbose_name='text from issuer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buddysystemconfiguration',
            name='enable_note_from_matcher',
            field=models.BooleanField(default=True, help_text='Allows matcher to reply with custom notes to the request issuer'),
        ),
        migrations.CreateModel(
            name='BuddyRequestMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('note', models.TextField(blank=True, verbose_name='text from matcher')),
                ('matcher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buddy_system_request_matches', to=settings.AUTH_USER_MODEL, verbose_name='matched by')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='buddy_system.buddyrequest', verbose_name='request')),
            ],
            options={
                'verbose_name': 'buddy request match',
                'verbose_name_plural': 'buddy request matches',
                'ordering': ('-created',),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
