# Generated by Django 4.2.4 on 2023-10-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0021_remove_buddyrequest_issuer_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequestmatch',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='text from matcher'),
        ),
    ]
