# Generated by Django 4.2.4 on 2023-10-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("universities", "0002_alter_university_name"),
        ("buddy_system", "0023_alter_buddyrequestmatch_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="buddyrequest",
            name="issuer_faculty",
            field=models.ForeignKey(
                default="15226bec-8bb6-4c84-ba54-f7474182731d",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="buddy_system_issued_requests",
                to="universities.faculty",
                verbose_name="issuer's faculty",
            ),
            preserve_default=False,
        ),
    ]
