# Generated by Django 4.2.4 on 2023-10-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_alter_university_name'),
        ('buddy_system', '0024_buddyrequest_issuer_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequestmatch',
            name='matcher_faculty',
            field=models.ForeignKey(default='15226bec-8bb6-4c84-ba54-f7474182731d', on_delete=django.db.models.deletion.RESTRICT, related_name='buddy_system_request_matches', to='universities.faculty', verbose_name="matcher's faculty"),
            preserve_default=False,
        ),
    ]
