# Generated by Django 4.2.7 on 2023-11-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0026_alter_buddyrequest_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddysystemconfiguration',
            name='matching_policy',
            field=models.CharField(choices=[('manual-by-editor', 'Manual by editors'), ('manual-by-member', 'Manual by members'), ('same-faculty', 'Manual by members with restriction to same faculty')], default='manual-by-editor', help_text='Manual by editors: Matching is done manually only by editors. <br />Manual by members: Matching is done manually directly by members. <br />Manual by members with restriction to same faculty: Matching is done manually by members themselves, but limited to the same faculty.', max_length=32),
        ),
        migrations.AlterField(
            model_name='buddysystemconfiguration',
            name='rolling_limit',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
