# Generated by Django 4.2.28 on 2026-07-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_system', '0031_alter_buddysystemconfiguration_rolling_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='issuer_gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('decline_to_state', 'decline to state'), ('other', 'other')], max_length=16, verbose_name="issuer's gender"),
        ),
        migrations.AddField(
            model_name='buddyrequest',
            name='same_gender_only',
            field=models.BooleanField(default=False, help_text='Require that only a buddy of the same gender as you can match with you. Available only if your profile gender is set to male or female.', verbose_name='only same-gender buddy'),
        ),
        migrations.AddField(
            model_name='buddysystemconfiguration',
            name='enable_same_gender_matching',
            field=models.BooleanField(default=False, help_text='Let issuers require that only a buddy of the same gender may match them. Only available to issuers whose profile gender is set to male or female.', verbose_name='enable same-gender matching'),
        ),
    ]
