# Generated by Django 4.2.7 on 2023-11-16 15:45

from django.db import migrations, models
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('pickup_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='49.1922443,16.6113382', max_length=63),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='place',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='pickup time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickupsystemconfiguration',
            name='rolling_limit',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
