# Generated by Django 4.2.7 on 2023-11-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup_system', '0002_pickuprequest_location_pickuprequest_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupsystemconfiguration',
            name='display_issuer_first_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickupsystemconfiguration',
            name='display_issuer_last_name',
            field=models.BooleanField(default=False),
        ),
    ]
