# Generated by Django 4.2.7 on 2023-12-17 10:04

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('pickup_system', '0006_pickupsystemconfiguration_default_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupsystemconfiguration',
            name='default_pickup_location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='49.194791469587045,16.608590483447188', help_text='This location will be used as a default pickup location displayed for new pickup requests.', max_length=63, null=True, verbose_name='default pickup location'),
        ),
    ]
