# Generated by Django 4.2.8 on 2024-01-18 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup_system', '0007_alter_pickupsystemconfiguration_default_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupsystemconfiguration',
            name='rolling_limit_window',
            field=models.DurationField(default=datetime.timedelta(days=84)),
        ),
        migrations.AlterField(
            model_name='pickupsystemconfiguration',
            name='rolling_limit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
