# Generated by Django 4.2.28 on 2026-03-03 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup_system', '0009_remove_pickupsystemconfiguration_rolling_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupsystemconfiguration',
            name='email_notify_issuer_delay',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Gives editors time to correct the match before the student is notified.', verbose_name='Delay before notifying the issuer'),
        ),
        migrations.AddField(
            model_name='pickupsystemconfiguration',
            name='email_notify_on_match',
            field=models.BooleanField(default=True, verbose_name='Send email notifications on match'),
        ),
    ]
