# Generated by Django 4.1 on 2022-10-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plugins', '0011_alter_basepluginconfiguration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfiguration',
            fields=[
                ('basepluginconfiguration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plugins.basepluginconfiguration')),
            ],
            options={
                'verbose_name': 'dashboard configuration',
                'verbose_name_plural': 'dashboard configurations',
            },
            bases=('plugins.basepluginconfiguration',),
        ),
    ]
