from __future__ import annotations

from django.db import models
from django.utils.translation import gettext_lazy as _


class Page(models.Model):
    file = models.CharField(primary_key=True, max_length=255, db_column="file", verbose_name=_("file"))
    title = models.CharField(max_length=255, db_column="title", verbose_name=_("title"))
    content_html = models.TextField(db_column="content_html", verbose_name=_("content"))
    content_plain = models.TextField(db_column="content_plain", verbose_name=_("content (plain)"))
    toc = models.TextField(db_column="toc", verbose_name=_("table of contents"))

    last_change = models.JSONField(db_column="last_change", verbose_name=_("last change"))

    class Meta:
        # generated by wiki dumper script, just queried by Django
        managed = False
        db_table = "wiki"
        verbose_name = _("page")
        verbose_name_plural = _("pages")

    def __str__(self):
        return self.title
