name: Docker Images Build

on:
  push:
    branches: [ develop, feature/*, main ]
  pull_request:
    branches: [ develop ]

jobs:
  build-docker-images:
    name: Build Docker images

    strategy:
      matrix:
        image: [fiesta, webpack]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Login to Github Packages
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GHCR_PAT }}

      - name: Build ${{ matrix.image }}/ image
        id: build_and_push
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          file: ${{ matrix.image }}/Dockerfile

          # tags: |
          #   oskardudycz/eventsourcing.nodejs.simple:latest
          #   ghcr.io/oskardudycz/eventsourcing.nodejs/simple:latest
          # # build on feature branches, push only on main branch
          # push: ${{ github.ref == 'refs/heads/main' }}
