name: ci

on:
  - push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
          registry: ${{ secrets.SCW_REGISTRY_ENDPOINT }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: fiesta/Dockerfile
          push: true
          tags: ${{ secrets.SCW_REGISTRY_ENDPOINT }}/web:latest
          # local github actions cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
