on:
  issues:
    types: [ opened, edited, deleted, transferred, closed, labeled, reopened, unlabeled, unlocked, locked ]


jobs:
  issues-to-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        path: repository

    - name: Checkout wiki code
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki

    - name: Query issues
      uses: helaili/github-graphql-action@2.0.1
      with:
        outputFile: issues.json
        query: '
          query($owner:String!, $name:String!, $label:String!) {
            repository(owner: "${{ github.repository_owner }}", name: "${{ github.repository_name }}") {
              issues(last: 100, orderBy: {field: CREATED_AT, direction: DESC}, labels: ["🟰 bug"]) {
                nodes {
                  number
                  resourcePath
                  titleHTML
                  state
                }
              }
            }
          }'

    - name: Render issues
      run: |
        ./repository/.github/scripts/render-issues-to-wiki.sh issues.json > wiki/Issues.md

    - name: Push to wiki
      run: |
        cd wiki
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Issues.md
        git diff-index --quiet HEAD || git commit -m "chore: issues update" && git push
